package com.jacky.launcher.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jacky.launcher.entity.GameEntity;

import com.jacky.launcher.dao.GameEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameEntityDaoConfig;

    private final GameEntityDao gameEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameEntityDaoConfig = daoConfigMap.get(GameEntityDao.class).clone();
        gameEntityDaoConfig.initIdentityScope(type);

        gameEntityDao = new GameEntityDao(gameEntityDaoConfig, this);

        registerDao(GameEntity.class, gameEntityDao);
    }
    
    public void clear() {
        gameEntityDaoConfig.clearIdentityScope();
    }

    public GameEntityDao getGameEntityDao() {
        return gameEntityDao;
    }

}
